openapi: 3.0.0
info:
  title: CC API
  description: API for creating bridge between ML (Machine Learning) and MD (Mobile Development) team
  version: 0.0.1
servers:
  - url: https://api.bangkit-c241-ps005.site/
paths:
  /auth/login:
    post:
      summary: Login
      description: Authenticate using username and password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Return JWT token to authenticate 
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: ok
                  data:
                    type: string
                    schema:
                      type: string
                        session_token:
                          type: string
